@echo off
setlocal EnableDelayedExpansion

title CookBook Setup
cd /d "%~dp0"

echo.
echo ============================================================
echo   CookBook - One-shot Docker Setup
echo ============================================================
echo.

REM --- Docker check ---
docker info >nul 2>&1
if errorlevel 1 (
    echo [ERROR] Docker is not running. Start Docker Desktop, then run this again.
    pause
    exit /b 1
)

REM --- Defaults ---
set "DEFAULT_DATA=%USERPROFILE%\CookBook"
set "DEFAULT_DB=%DEFAULT_DATA%\db"
set "DEFAULT_MODELS=%DEFAULT_DATA%\models"
set "DEFAULT_DATASET=%DEFAULT_DATA%\dataset"
set "DEFAULT_RECIPES=%DEFAULT_DATA%\recipes"

echo Storage paths (press Enter to accept defaults):
echo.

set /p "HOST_DB_DIR=SQLite database folder [%DEFAULT_DB%]: "
if "!HOST_DB_DIR!"=="" set "HOST_DB_DIR=%DEFAULT_DB%"

set /p "HOST_OLLAMA_DIR=Trained / Ollama models folder [%DEFAULT_MODELS%]: "
if "!HOST_OLLAMA_DIR!"=="" set "HOST_OLLAMA_DIR=%DEFAULT_MODELS%"

set /p "HOST_DATASET_DIR=Dataset folder (videos + transcripts) [%DEFAULT_DATASET%]: "
if "!HOST_DATASET_DIR!"=="" set "HOST_DATASET_DIR=%DEFAULT_DATASET%"

set /p "HOST_RECIPES_DIR=Recipe repository folder [%DEFAULT_RECIPES%]: "
if "!HOST_RECIPES_DIR!"=="" set "HOST_RECIPES_DIR=%DEFAULT_RECIPES%"

set "HOST_WORKING_DIR=%DEFAULT_DATA%\working"
set "HOST_WHISPER_CACHE_DIR=%DEFAULT_DATA%\whisper-cache"

echo.
echo GPU:
echo   1) NVIDIA GPU (recommended - Whisper + Ollama)
echo   2) CPU only (slower transcription, no GPU for Ollama)
set /p "GPU_CHOICE=Choose [1]: "
if "!GPU_CHOICE!"=="" set "GPU_CHOICE=1"
if "!GPU_CHOICE!"=="2" (
    set "USE_GPU="
    set "WHISPER_DEVICE=cpu"
) else (
    set "USE_GPU=1"
    set "WHISPER_DEVICE=cuda"
)

echo.
echo What should we do after setup?
echo   1) Build and start the full stack (web + Ollama)
echo   2) Build only (no start)
echo   3) Phase 0 only - build image, no background services
set /p "RUN_CHOICE=Choose [1]: "
if "!RUN_CHOICE!"=="" set "RUN_CHOICE=1"

set /p "FORMATTER_MODEL=Ollama formatter model [cookbook-formatter]: "
if "!FORMATTER_MODEL!"=="" set "FORMATTER_MODEL=cookbook-formatter"

set /p "WHISPER_MODEL=Whisper model name [large-v3]: "
if "!WHISPER_MODEL!"=="" set "WHISPER_MODEL=large-v3"

REM --- Create host directories ---
for %%D in ("!HOST_DB_DIR!" "!HOST_OLLAMA_DIR!" "!HOST_DATASET_DIR!" "!HOST_RECIPES_DIR!" "!HOST_WORKING_DIR!" "!HOST_WHISPER_CACHE_DIR!" "!HOST_DATASET_DIR!\raw" "!HOST_DATASET_DIR!\transcripts" "!HOST_DATASET_DIR!\metadata") do (
    if not exist %%D mkdir %%D 2>nul
)

REM --- Write .env (convert backslashes for Docker Compose on Windows) ---
call :ToDockerPath "!HOST_DB_DIR!" HOST_DB_DOCKER
call :ToDockerPath "!HOST_OLLAMA_DIR!" HOST_OLLAMA_DOCKER
call :ToDockerPath "!HOST_DATASET_DIR!" HOST_DATASET_DOCKER
call :ToDockerPath "!HOST_RECIPES_DIR!" HOST_RECIPES_DOCKER
call :ToDockerPath "!HOST_WORKING_DIR!" HOST_WORKING_DOCKER
call :ToDockerPath "!HOST_WHISPER_CACHE_DIR!" HOST_WHISPER_CACHE_DOCKER

> ".env" (
    echo # Generated by CookBook-Setup.bat - %DATE% %TIME%
    echo MODE=web
    echo.
    echo # Host bind-mount paths
    echo HOST_DB_DIR=!HOST_DB_DOCKER!
    echo HOST_OLLAMA_DIR=!HOST_OLLAMA_DOCKER!
    echo HOST_DATASET_DIR=!HOST_DATASET_DOCKER!
    echo HOST_RECIPES_DIR=!HOST_RECIPES_DOCKER!
    echo HOST_WORKING_DIR=!HOST_WORKING_DOCKER!
    echo HOST_WHISPER_CACHE_DIR=!HOST_WHISPER_CACHE_DOCKER!
    echo HOST_FORMATTER_MODEL_DIR=..
    echo.
    echo WHISPER_MODEL=!WHISPER_MODEL!
    echo WHISPER_DEVICE=!WHISPER_DEVICE!
    echo.
    echo FORMATTER_PROVIDER=ollama
    echo OLLAMA_HOST=http://ollama:11434
    echo FORMATTER_MODEL=!FORMATTER_MODEL!
    echo FORMATTER_GGUF_PATH=/models/cookbook-formatter.gguf
    echo FORMATTER_MODELFILE=/models/Modelfile
    echo.
    echo WEB_PORT=8080
    echo TESTING_GUI_PORT=8081
    echo DEPLOYMENT_GUI_PORT=8082
    echo DOWNLOAD_LIMIT=50
)

echo.
echo Wrote .env with your paths.
echo   Database:  !HOST_DB_DIR!
echo   Models:    !HOST_OLLAMA_DIR!
echo   Dataset:   !HOST_DATASET_DIR!
echo   Recipes:   !HOST_RECIPES_DIR!
echo   GPU:       !WHISPER_DEVICE!
echo.

if "!RUN_CHOICE!"=="3" (
    echo Building cookbook image (Phase 0^)...
    docker compose -f docker-compose.phase0.yml build
    if errorlevel 1 goto :Failed
    echo.
    echo Build complete. Run batch jobs manually, e.g.:
    echo   docker compose -f docker-compose.phase0.yml run --rm -e MODE=download cookbook --urls-file /data/dataset/urls.txt
    goto :Done
)

set "COMPOSE_FILES=-f docker-compose.yml"
if defined USE_GPU set "COMPOSE_FILES=!COMPOSE_FILES! -f docker-compose.gpu.yml"

echo Building images...
docker compose !COMPOSE_FILES! build
if errorlevel 1 goto :Failed

if "!RUN_CHOICE!"=="2" goto :Done

echo Starting stack...
docker compose !COMPOSE_FILES! up -d
if errorlevel 1 goto :Failed

if defined USE_GPU (
    echo.
    echo Waiting for Ollama to start...
    timeout /t 8 /nobreak >nul
    if exist "..\cookbook-formatter.gguf" (
        echo Local GGUF found — registering !FORMATTER_MODEL! from repo root...
        docker compose !COMPOSE_FILES! exec -T ollama ollama create !FORMATTER_MODEL! -f /models/Modelfile
    ) else if "!FORMATTER_MODEL!"=="cookbook-formatter" (
        echo [WARN] ..\cookbook-formatter.gguf not found. Place the GGUF at repo root and restart ollama.
    ) else (
        echo Pulling formatter model: !FORMATTER_MODEL!
        docker compose !COMPOSE_FILES! exec -T ollama ollama pull !FORMATTER_MODEL!
    )
)

:Done
echo.
echo ============================================================
echo   Setup complete
echo ============================================================
echo   Production UI:  http://localhost:8080  (when MODE=web is ready^)
echo   Config file:    %CD%\.env
echo.
echo   Useful commands (run from this folder^):
echo     docker compose !COMPOSE_FILES! ps
echo     docker compose !COMPOSE_FILES! logs -f cookbook
echo     docker compose -f docker-compose.phase0.yml run --rm -e MODE=download cookbook --urls-file /data/dataset/urls.txt
echo.
pause
exit /b 0

:Failed
echo.
echo [ERROR] A docker command failed. Check output above.
pause
exit /b 1

:ToDockerPath
set "RAW=%~1"
set "RAW=!RAW:\=/!"
REM Docker Desktop on Windows expects C:/path not /c/path
set "%~2=!RAW!"
exit /b 0
